task default: ['exercise10:run_tests', 'exercise10:format_code']

namespace :exercise10 do
  desc 'Runs all unit tests using rspec'
  task :run_tests do
    `rspec`
  end

  desc 'Automatically corrects linting issues using rubocop'
  task :format_code do
    `rubocop -a`
  end

  desc 'Lists files in a directory, optionally you can pass a glob to filter by in the format *.ext'
  task :list, [:path, :glob] do |t, args|
    args.with_defaults(glob: '*.*')
    puts `ls #{args['path']}#{args['glob']}`
  end
end
